//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Калькулятор_посчитайкин.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Калькулятор_посчитайкин.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string PoschitaikinMain_Bs__0 {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Bs__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % = .
        /// </summary>
        internal static string PoschitaikinMain_btnper_Click_ {
            get {
                return ResourceManager.GetString("PoschitaikinMain_btnper_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string PoschitaikinMain_btnpm_Click__0 {
            get {
                return ResourceManager.GetString("PoschitaikinMain_btnpm_Click__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dec (10).
        /// </summary>
        internal static string PoschitaikinMain_cbsist_SelectionChangeCommitted_Dec__10_ {
            get {
                return ResourceManager.GetString("PoschitaikinMain_cbsist_SelectionChangeCommitted_Dec__10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string PoschitaikinMain_Del__0 {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Del__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string PoschitaikinMain_Delstr__0 {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Delstr__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string PoschitaikinMain_Poschitaikin_main_Load__0 {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Poschitaikin_main_Load__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  = .
        /// </summary>
        internal static string PoschitaikinMain_Resultat_ {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Resultat_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ).
        /// </summary>
        internal static string PoschitaikinMain_Resultat__ {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Resultat__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   {.
        /// </summary>
        internal static string PoschitaikinMain_Resultat____ {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Resultat____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mean(.
        /// </summary>
        internal static string PoschitaikinMain_Resultat_mean_ {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Resultat_mean_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string PoschitaikinMain_Twooper__ {
            get {
                return ResourceManager.GetString("PoschitaikinMain_Twooper__", resourceCulture);
            }
        }
    }
}
